campaign order admin edit  fix
hejcz/gollum-shop-frontend pull request #6
Opened 2022-08-12 16:06 UTC by bones-pc

zamowienia rozpoznawane po order uuid (wcześniej campaign_uuid + user_id - brany z tokena powodował błąd w zapisie kwoty zapłaconej)

2022-08-12 16:10 UTC, hejcz commented on src/api/rest_api.ts
>          campaign_uuid: order.campaign_uuid,
Czy w takim razie tu jest potrzebny jeszcze campaign uuid w payloadzie?

2022-08-14 14:09 UTC, hejcz requested changes

2022-08-14 14:09 UTC, hejcz commented on src/stores.ts
> +  "http://localhost:3000/api/"
Tego nie chcemy mergować do mastera.

2022-08-14 14:10 UTC, hejcz commented
Nazwa PR nie odnosi się do commitów.

2022-08-18 00:36 UTC, closed without merging

2022-08-18 00:36 UTC, bones-pc commented
powtórka w inne PR