Profil
hejcz/gollum-shop-frontend pull request #7
Opened 2022-08-12 23:53 UTC by bones-pc

formatka dla profilu użytkownika wraz z metodami PATCH

2022-08-14 14:12 UTC, hejcz commented on src/api/mock_data/orders.ts
> +      order_uuid: "9vn20986h764v",
Te commity są powtórzone z drugim PR. Nie da się od mastera odbić tej jednej zmiany? Albo zamknąć tamten PR jeśli mają wejść razem?

2022-08-14 14:12 UTC, hejcz commented on src/App.svelte
> +      <Route path="/users/profile">
npm run format

2022-08-14 14:16 UTC, hejcz requested changes

2022-08-14 14:16 UTC, hejcz commented on src/Navigation.svelte
> +                <Link to="/users/profile">{$_("nav.userprofile")}</Link>
Zarządzanie userami a informacje o profilu to chyba powinny być osobne podstrony? Tzn Przemek chciał moim zdaniem zachować to zarządzanie userami bo tam ich aktywuje / blokuje.

2022-08-14 14:16 UTC, hejcz commented on src/api/rest_api.ts
> +    uuid: user.uuid,
to przepakowanie chyba nie ma sensu? W innych miejscach to robiłem bo to co zwracał backend rozjeżdżało się z tym co miałem zrobione na froncie.

2022-08-14 14:16 UTC, hejcz commented on src/api/rest_api.ts
> +        // return response_json.map(backend_user_profile_to_frontend_user_profile);
do wywalenia.

2022-08-14 14:16 UTC, hejcz commented on src/api/rest_api.ts
> +  updateUserProfile(username: string, firstname: string, lastname: string, email: string, phone: string, street: string, zip: string, city: string, inpost: string): Promise<boolean> {
lepiej chyba przekazać tu updtaedProfile: UserProfile niż mieć tyle parametrów.

2022-08-18 00:18 UTC, bones-pc commented
> Zarządzanie userami a informacje o profilu to chyba powinny być osobne podstrony? Tzn Przemek chciał moim zdaniem zachować to zarządzanie userami bo tam ich aktywuje / blokuje. 

nie znam jeszcze (wogole) Svelete żeby to ogarnać :|

2022-08-18 00:18 UTC, bones-pc commented
> npm run format 

done

2022-08-18 00:19 UTC, bones-pc commented
> Te commity są powtórzone z drugim PR. Nie da się od mastera odbić tej jednej zmiany? Albo zamknąć tamten PR jeśli mają wejść razem? 

tak tamten mozna zamknąc - to porawka która musi wejść żeby Przemek poprawnie zapisywał wpłaty

2022-08-18 00:23 UTC, bones-pc commented on src/api/mock_data/orders.ts
> +      order_uuid: "9vn20986h764v",
tamten zamkne w takim razie - muszę je robić za każdym razem bo mi wywala z jakiś przyczyn masę błędów :|

2022-12-28 01:10 UTC, closed without merging